### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by joneshf** [purescript/purescript-typelevel-prelude#7]
The README states that this library is compatible with compiler versions >= 0.10.5. A few questions:

1. Is there a reason 0.10.5 was chosen?
1. How strongly do we feel this library need to stay backward compatible to 0.10.5?
1. How would we feel about compiling with different versions on travis?

**Comment by garyb** [comment]
1. That's when custom kinds were introduced, and somewhere around there the some `Symbol`-related compiler-soved classes too
2. I don't think that's necessary really, we don't do that anywhere else :smile:
3. Maybe moot

I think the notice was more about saying this library won't work with older compilers, when it was first introduced. We can probably drop the notice now, since hopefully everyone is on 0.11.x anyway... 🤞

**Comment by joneshf** [comment]
Gotcha. Thanks!
